### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by ghost** [rubrickshq/CodeUI#1]
I would like to add a code of conduct developed for your repository. Please let me know if it is okay to proceed. Please assign to me and add GSSoC24 Ext labels.

**Comment by beRajeevKumar** [comment]
Hey, @KiranBaliga, I just noticed that our project doesn't have any Code of Conduct. Thank you for making me aware. 
Do it right away 🚀

**Comment by beRajeevKumar** [comment]
If you have any doubts, then join this below discord server for better communication.
https://discord.gg/eXrQqgRX

**Comment by KiranBaliga** [comment]
@beRajeevKumar Please review the PR and action accordingly. Thank you.

#please add the required labels to the PR as well!
