### ISSUE TITLE
[BUG] Issue Title: Empty Container in Project Section

### ISSUE THREAD

**Issue by ghost** [rubrickshq/CodeUI#236]
### Description

The container in the project section currently lacks an image, leaving it blank. I can take up the task of updating it with the correct image or managing the empty state. Please assign this issue to me for resolution.

### Screenshots

![Screenshot 2024-10-10 070936](https://github.com/user-attachments/assets/1870b30f-d935-4b8e-bc0a-599934abe523)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/beRajeevKumar/Frontend_Mentor/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by snehhhcodes** [comment]
@beRajeevKumar hey please assign this issue to me i can fix it.

**Comment by beRajeevKumar** [comment]
@snehhhcodes, do it🚀
