### ISSUE TITLE
[BUG] Enhancement of Login and Signup Pages

### ISSUE THREAD

**Issue by ghost** [rubrickshq/CodeUI#266]
### Description

The login and signup pages currently lack CSS styling, leading to a visually unappealing design that does not engage users. This results in a poor user experience, as the pages do not align with the overall user interface of the website. Elements like buttons and input fields appear bland and fail to attract attention, causing potential users to feel disconnected from the site.

### Screenshots

[screen-capture (1).webm](https://github.com/user-attachments/assets/af833360-ade3-4c36-8210-98c27b8067fe)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/beRajeevKumar/Frontend_Mentor/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by beRajeevKumar** [comment]
Go for it
