### ISSUE TITLE
[BUG] Incomplete FAQ Section Functionality

### ISSUE THREAD

**Issue by ghost** [rubrickshq/CodeUI#267]
### Description

The FAQ section presents users with a list of questions, but clicking the plus icon to view answers yields no responses. This issue creates user frustration, as they cannot access essential information about services or policies. The lack of answers may also deter users from engaging further with the website, leading them to seek help elsewhere. 

To improve the user experience, it is crucial to provide clear and informative answers that display correctly when the plus icon is clicked.

### Screenshots

[screen-capture (2).webm](https://github.com/user-attachments/assets/dd49ae43-d159-4bd4-8c33-bc4024b6e808)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/beRajeevKumar/Frontend_Mentor/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by beRajeevKumar** [comment]
go for it 🚀
